apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    component: server
spec:
  containers:
    - name: server
      image: aritradevelops/hush_app_server
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: server-env