/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class CallsQuery {
  /**
   * Fetches the ongoing calls for an user
   * @param {uuid} $1 - the user's id
   */
  ongoing() {
    return `SELECT c.* FROM calls c WHERE c.ended_at IS NULL AND EXISTS ( SELECT 1 FROM channel_participants cp WHERE c.channel_id = cp.channel_id AND cp.user_id = $1::uuid AND cp.deleted_at IS NULL )`;
  }
}
export default new CallsQuery();