/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class CallQuery {
  /**
   * Fetches all running call for an user
   * @param {uuid} $1 - the user's id
   */
  getActiveCalls() {
    return `WITH user_channel_ids AS ( SELECT cp.channel_id FROM channel_participants cp WHERE cp.user_id = $1::uuid AND cp.deleted_at IS NULL ) SELECT call.* FROM calls call WHERE call.status = 0 AND call.channel_id IN ( SELECT channel_id FROM user_channel_ids );`;
  }
}
export default new CallQuery();