/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class CallQuery {
  /**
   * Fetches running calls for a given user
   * @param {uuid} $1 - the user's id
   */
  getRunningCallsForUser() {
    return `SELECT DISTINCT call.* FROM calls call JOIN channel_participants cp ON call.channel_id = cp.channel_id WHERE cp.user_id = $1::uuid AND cp.deleted_at IS NULL AND call.ended_at IS NULL;`;
  }
}
export default new CallQuery();