/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class ChannelsQuery {
  /**
   * No documentation provided.
   */
  getAllChannelIdsForUser() {
    return `SELECT dm.id FROM direct_messages dm WHERE dm.member_ids @> ARRAY[$1]::uuid[] UNION SELECT g.id FROM groups g WHERE g.member_ids @> ARRAY[$1]::uuid[]`;
  }
}
export default new ChannelsQuery();