/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class ChannelParticipantQuery {

}
export default new ChannelParticipantQuery();