/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class ContactQuery {
  /**
   * Add a new contact to the user's contact list and create channel for them
   * @param {uuid} $1 - The user's id
   * @param {uuid} $2 - The new contact's id
   */
  addNewContact() {
    return `WITH new_channel AS ( INSERT INTO channels (type, created_by) VALUES ('0', $1::UUID) RETURNING id ) INSERT INTO contacts (name, channel_id, user_id, status, created_by) SELECT name, new_channel.id, $1::UUID, '2'::contacts_status_enum, $2::UUID FROM users, new_channel WHERE users.id = $1::UUID UNION ALL SELECT name, new_channel.id, $2::UUID, '1'::contacts_status_enum, $1::UUID FROM users, new_channel WHERE users.id = $2::UUID`;
  }
}
export default new ContactQuery();