/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class UserQuery {
  /**
   * Find new users that are not in the contacts list
   * @param {uuid} $1 - Id of the user initiating the request
   * @param {string} $2 - Search query
   */
  findNewUsers() {
    return `SELECT u.id, u.email, u.name, u.avatar, ts_rank(u.search, to_tsquery($2)) AS rank FROM users u WHERE u.id NOT IN ( SELECT c.user_id FROM contacts c WHERE c.created_by = $1 ) AND u.id != $1 AND u.status = '2' AND u.deleted_at IS NULL AND u.search @@ to_tsquery($2) ORDER BY rank DESC;`;
  }
}
export default new UserQuery();