/**
 * ⚠️ This file is auto-generated with `npm run cli g:query`
 * Do NOT edit this file manually. Changes will be overwritten.
 */
export class UserChatInteractionQuery {
  /**
   * No documentation provided.
   */
  findNotInteractedChats() {
    return `SELECT uci.id, uci.channel_id, row_to_json(chat) as chat FROM user_chat_interactions uci LEFT JOIN chats chat ON chat.id = uci.chat_id AND chat.channel_id = uci.channel_id WHERE uci.created_by = $1::uuid AND uci.status = '0'::user_chat_interactions_status_enum AND uci.deleted_at IS NULL`;
  }

  /**
   * No documentation provided.
   */
  findNotSeenChats() {
    return `SELECT uci.id, uci.channel_id, row_to_json(chat) as chat FROM user_chat_interactions uci LEFT JOIN chats chat ON chat.id = uci.chat_id AND chat.channel_id = uci.channel_id WHERE uci.created_by = $1::uuid AND uci.channel_id = $2::uuid AND uci.status != '2'::user_chat_interactions_status_enum AND uci.deleted_at IS NULL`;
  }
}
export default new UserChatInteractionQuery();