name: 🔒 Security Vulnerability
description: Report a security vulnerability
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: Security vulnerabilities should be reported privately to maintain security.**
        
        Please **DO NOT** create public issues for security vulnerabilities. Instead, please email us directly at security@hush.swiftgeek.in or use GitHub's private vulnerability reporting feature.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical (Immediate threat, data breach)
        - High (Significant security risk)
        - Medium (Moderate security concern)
        - Low (Minor security issue)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - Authentication/Authorization
        - Encryption/Decryption
        - File Upload/Download
        - Real-time Communication
        - Database
        - API Endpoints
        - Client-side Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: Provide a detailed description of the security issue...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this vulnerability is exploited?
      placeholder: Describe the potential consequences...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        **⚠️ DO NOT include actual exploit code in public issues**
        
        Provide general steps without revealing sensitive details...
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have any suggestions for fixing this issue?
      placeholder: Describe any potential solutions or workarounds...

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Security vulnerabilities should be reported responsibly
      options:
        - label: I understand this is a security issue and should be reported privately
          required: true
        - label: I will not publicly disclose this vulnerability until it's been fixed
          required: true

  - type: markdown
    attributes:
      value: |
        ## 🔒 Private Reporting
        
        For security vulnerabilities, please contact us privately:
        - **Email**: security@hush.swiftgeek.in
        - **GitHub Security Advisory**: Use GitHub's private vulnerability reporting
        - **PGP Key**: Available upon request for encrypted communication
        
        We appreciate your responsible disclosure and will work to address security issues promptly.
